import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createPublicClient, createWalletClient, http, type Hex } from 'viem';
import { avalancheFuji } from 'viem/chains';
import { privateKeyToAccount } from 'viem/accounts';
import { readConfig } from '../apps/gateway/src/config.ts';
import { FUJI_USDC } from '../packages/domain/src/index.ts';
const config = readConfig();
if (!config.FUJI_PRIVATE_KEY) throw new Error('Set FUJI_PRIVATE_KEY to a funded Fuji test wallet');
if (config.MARKET_ADDRESS) throw new Error('MARKET_ADDRESS is already configured; refusing an accidental second deployment');
const account = privateKeyToAccount(config.FUJI_PRIVATE_KEY);
const client = createPublicClient({ chain: avalancheFuji, transport: http(config.FUJI_RPC_URL) });
if (await client.getChainId() !== 43113) throw new Error('Deploy is restricted to Avalanche Fuji');
const wallet = createWalletClient({ account, chain: avalancheFuji, transport: http(config.FUJI_RPC_URL) });
const artifact = JSON.parse(await readFile('contracts/out/AccessMarket.sol/AccessMarket.json', 'utf8'));
const hash = await wallet.deployContract({ abi: artifact.abi, bytecode: artifact.bytecode.object as Hex, args: [FUJI_USDC, account.address] });
console.log(`Deployment sent: ${hash}`);
const receipt = await client.waitForTransactionReceipt({ hash, confirmations: config.PAYMENT_CONFIRMATIONS });
if (receipt.status !== 'success' || !receipt.contractAddress) throw new Error('Deployment failed');
await mkdir('deployments', { recursive: true });
await writeFile('deployments/fuji.json', JSON.stringify({ chainId: 43113, market: receipt.contractAddress, token: FUJI_USDC, operator: account.address, transactionHash: hash, blockNumber: receipt.blockNumber.toString() }, null, 2) + '\n');
console.log(`Set MARKET_ADDRESS=${receipt.contractAddress} in .env`);
