import { readFile, mkdir, writeFile } from 'node:fs/promises';
const artifact = JSON.parse(await readFile('contracts/out/AccessMarket.sol/AccessMarket.json', 'utf8'));
await mkdir('packages/avalanche/src', { recursive: true });
await writeFile('packages/avalanche/src/abi.ts', `// Generated by pnpm contracts:build. Do not edit.\nexport const accessMarketAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`);
